# Change these first
owner: PhiloNL # Your GitHub username
repo: codebird-uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Quotify
    url: https://quotify.codebird.nl
    expectedStatusCodes:
      - 301
    assignees:
      - PhiloNL

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.codebird.nl
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Codebird
  introTitle: "Uptime monitor for Codebird services"
  #introMessage: 
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
